# ref: https://docs.github.com/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Bug Report
description: Bug report (Users)
title: "[Bug]: "
labels: ["bug"]

body:
  - type: checkboxes
    id: no-duplicate-feature
    attributes:
      label: Check for duplicate issues
      options:
        - label: I have verified that there are no open duplicate issues.
          required: true

  - type: dropdown
    id: version
    attributes:
      label: What version of ESLifier are you using?
      options:
        - 0.5.13-alpha
        - 0.5.11-alpha
        - 0.5.10-alpha
        - 0.5.7-alpha
        - 0.5.3-alpha
        - Other (Specify in Description)
    validations:
      required: true

  - type: textarea
    id: describe-the-problem
    attributes:
      label: A Brief Description of the Problem.
      description: |
        Please briefly describe the issue you are experiencing. If the program is not patching an asset file correctly please detail what mod the file is from
        and what mod you're compacting the FormIDs for that should be causing the file to be patched. If a mod has errors in xEdit after compacting,
        please confirm that the issue doesn't exist on the pre-compacted version with the exact same mods loaded in xEdit before reporting it.
    validations:
      required: true

  - type: textarea
    id: reproducing-the-problem
    attributes:
      label: Provide Instructions on Reproducing the Problem
      description: |
        When submitting a bug report, please provide the steps that another user should take to reproduce the same issue, assuming that the bug needs any specific
        steps to recreate. Always write your report under the assumption that the developers have no information about the bug.
    validations:
      required: false

  - type: textarea
    id: relevant-files
    attributes:
      label: Provide Relevant Files
      description: |
        If it is an issue with ESLifier crashing the ESLifier.log file should be submitted.
        If you want you can include the entire ESLifier_Data folder zipped.
      placeholder: |
        ESLifier.log 
    validations:
      required: false
    
