# ref: https://docs.github.com/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Bug Report
description: Bug report (Users)
title: "[Bug]: "
labels: ["bug"]

body:
  - type: checkboxes
    id: no-duplicate-feature
    attributes:
      label: Check for duplicate issues
      options:
        - label: I have verified that there are no open duplicate issues.
          required: true
      
  - type: checkboxes
    id: latest-version
    attributes:
      label: Are you on the latest version?
      options: 
        - label: I have double checked that I am on the latest version of ESLifier.
          required: true

  - type: textarea
    id: describe-the-problem
    attributes:
      label: A Brief Description of the Problem.
      description: |
        Please briefly describe the issue you are experiencing. If the program is not patching an asset file correctly please detail what mod the file is from
        and what mod you're compacting the FormIDs for that should be causing the file to be patched. If a mod has errors in xEdit after compacting,
        please confirm that the issue doesn't exist on the pre-compacted version with the exact same mods loaded in xEdit before reporting it.
    validations:
      required: true

  - type: textarea
    id: relevant-files
    attributes:
      label: Provide Relevant Files
      description: |
        General issues need to provide the ESLifier.log located in the ESLifier_Data folder. Make sure the log is not empty and contains the issue.
        Note that the log is reset each time ESLifier is started.
        If you want you can include the entire ESLifier_Data folder zipped.
      placeholder: |
        ESLifier.log 
    validations:
      required: false
    
