# ref: https://docs.github.com/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: File Patch Request
description: New File Patch Request
title: "[Patch Request]: "
labels: ["Patch Request"]

body:
  - type: textarea
    id: patch-request
    attributes:
      label: What File Does ESLifier Need to Patch?
      description: |
        What file do you need ESLifier to patch when compacting FormIDs? Also, provide a link to a mod that uses the file or a link to the possible framework mod that
        defines the file (i.e. Spell Perk Item Distributor). Nexus Mods links are preferred.
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        Below is a list of currently patched file types. If you're making a request for one of them because it is not being patched correctly then please make a bug report instead. 

        
        **Currently Patched File Types:**
        - **.ini:**  
          - Keyword Item Distributor
          - Base Object Swapper
          - Spell Perk Item Distributor
          - Seasons of Skyrim
          - Payload Interpreter
          - ENB Lights for Effects Shaders
          - Description Framework  
          - Seasons of Skyrim
          - Payload Interpreter
          - SkyPatcher  
          - DtryKeyUtil  
          - Poise Breaker  
          - Valhalla Combat  
          - AutoBody  
          - Various States of Undress
          - Form List Manipulator
          - Leveled List Object Swapper
          - Item Property Manipulator
          - Music Type Distributor
          - Completionist
          - KreatE (with caveats)
          - Remember Lockpick Angle - Updated
          - Light Placer  
          
        - **.json:**  
          - Open Animation Replacer (OAR)  
          - MCM Helper  
          - Dynamic Key Activation Framework NG  
          - Smart Harvest Auto NG AutoLoot  
          - PapyrusUtil's StorageDataUtil  
          - Custom Skills Framework (old format CustomSkill.<name>.config.txt supported)
          - Core Impact Framework
          - Object Impact Framework
          - Dynamic String Distributor  
          - Dynamic Armor Variants  
          - Inventory Injector  
          - Immersive Equipment Display  
          - Spell Research
          - Perk Adjuster
          - Player Equipment Manager  
          - Skyrim Unbound  
          - Creature Framework  
          - CoMAP  
          - OBody NG  
          - SL Configs
          - OStim Standalone
          - Race Compatibility SKSE
          - Rain Extinguishes Fires
          - Immersive Hair Growth and Styling
          - Inte's Skyrim - Utility Mod
          - dse-display-model
          - CaptiveFollowers
          - Generic Synthesis Patcher (GSP)
          
        - **.toml:**  
          - Dynamic Animation Casting  
          - Precision  
          - Loki Poise  
          - True Directional Movement 
          - Actor Value Generator
          
        - **.pex:**  
          - Compiled script files  
          
        - **.jslot:**  
          - RaceMenu Presets  
        
        - **_conditions.txt:**  
          - Dynamic Animation Replacer (DAR)  
        
        - **_srd.:**  
          - Sound Record Distributor  
          
        - **facegeom's .nif:**  
          - Texture paths in face mesh files  
        
        - **voice, facetint, facegeom:**  
          - These file names are patched  
        
        - **.seq:**  
          - SEQ files  
          

          
  - type: checkboxes
    id: no-duplicate-feature
    attributes:
      label: Check for Duplicate Requests
      options:
        - label: I have verified that there are no duplicate Requests and that the file is not present in the above list.
          required: true
    
