# ref: https://docs.github.com/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: File Patch Request
description: New File Patch Request
title: "[Patch Request]: "
labels: ["Patch Request"]

body:
  - type: textarea
    id: patch-request
    attributes:
      label: What File Does ESLifier Need to Patch?
      description: |
        What file do you need ESLifier to patch when compacting FormIDs? Also, provide a link to a mod that uses the file or a link to the possible framework mod that
        defines the file (i.e. Spell Perk Item Distributor). Nexus Mods links are preferred.
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        Make sure to double check that the file you're requesting a patch for is not already in the list on Nexus or the GitHub README.md. If the file is, then instead
        you should make a bug report if the file is not being patched.
          
  - type: checkboxes
    id: no-duplicate-feature
    attributes:
      label: Check for Duplicate Requests
      options:
        - label: I have verified that there are no duplicate Requests and that the file is not present in the above list.
          required: true
    
